<?xml version="1.0" encoding="ASCII" standalone="yes"?>
<!DOCTYPE Scatalog [
	<!ELEMENT Scatalog (Site*)>
	<!ATTLIST Scatalog VERSION CDATA #REQUIRED>
	<!ELEMENT Site (Server+)>
	<!ATTLIST Site name (BNL | LBL) #REQUIRED>
	<!ATTLIST Site description CDATA #IMPLIED>
	<!ATTLIST Site URI CDATA #IMPLIED>
	<!ELEMENT Server (Host+)>
	<!ATTLIST Server scope (Master | Admin | User | Production | Analysis) #REQUIRED>
	<!ELEMENT Host (Access+)>
	<!ATTLIST Host name CDATA #REQUIRED>
	<!ATTLIST Host dbType CDATA #IMPLIED>
	<!ATTLIST Host dbName CDATA #REQUIRED>
	<!ATTLIST Host port CDATA #IMPLIED>
	<!ELEMENT Access EMPTY>
	<!ATTLIST access user CDATA #IMPLIED>
	<!ATTLIST access pass CDATA #IMPLIED>
]>



<Scatalog version="1.0.1">

	<Server scope="Production" user="starreco,priv2" accessMode="read">

		<Host name="star-db01.sdcc.bnl.gov" port="3316" machinePower="1.0" /> 
		<Host name="star-db02.sdcc.bnl.gov" port="3316" machinePower="1.0" /> 
		<Host name="star-db03.sdcc.bnl.gov" port="3316" machinePower="1.0" /> 
		<Host name="star-db04.sdcc.bnl.gov" port="3316" machinePower="1.0" /> 
<!--
		<Host name="star-db02.rcf.bnl.gov" port="3316" machinePower="1.0" /> 
		<Host name="star-db03.rcf.bnl.gov" port="3316" machinePower="1.0" />
		<Host name="star-db07.rcf.bnl.gov" port="3316" machinePower="1.0" />
		<Host name="star-db08.rcf.bnl.gov" port="3316" machinePower="1.0" />
//-->
	</Server>

	<Server scope="Analysis" accessMode="read">

		<Host name="star-db05.sdcc.bnl.gov" port="3316" machinePower="1.0" /> 
		<Host name="star-db06.sdcc.bnl.gov" port="3316" machinePower="1.0" /> 
		<Host name="star-db07.sdcc.bnl.gov" port="3316" machinePower="1.0" /> 
		<Host name="star-db08.sdcc.bnl.gov" port="3316" machinePower="1.0" /> 

<!--
    <Host name="star-db05.rcf.bnl.gov" port="3316" machinePower="1.0" />
		<Host name="star-db06.rcf.bnl.gov" port="3316" machinePower="1.0" />
		<Host name="star-db09.rcf.bnl.gov" port="3316" machinePower="1.0" />
		<Host name="star-db10.rcf.bnl.gov" port="3316" machinePower="10.0" />
//-->
	</Server>	

	<Server scope="Analysis" user="jwebb,dunlop,genevb,dmitry" accessMode="read">

		<Host name="star-db12.sdcc.bnl.gov" port="3316" machinePower="1.0" /> 
		<Host name="star-db08.sdcc.bnl.gov" port="3316" machinePower="1.0" /> 
<!--
		<Host name="star-db07.rcf.bnl.gov" port="3316" machinePower="1.0" />
		<Host name="star-db06.rcf.bnl.gov" port="3316" machinePower="1.0" />
		<Host name="star-db09.rcf.bnl.gov" port="3316" machinePower="10.0" /> 
		<Host name="star-db10.rcf.bnl.gov" port="3316" machinePower="10.0" /> 
		<Host name="star-db11.rcf.bnl.gov" port="3316" machinePower="10.0" />
//-->

	</Server>

	<Server scope="Analysis" accessMode="write">
		<Host name="robinson.star.bnl.gov" port="3306"/>
	</Server>

	<Server scope="Production" user="starreco" accessMode="write">
		<Host name="robinson.star.bnl.gov" port="3306"/>
	</Server>

</Scatalog>
